"""add reading pace multiplier

Revision ID: 0667c327f7a0
Revises: 670a5f527ca5
Create Date: 2026-08-15 19:56:44.885402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0667c327f7a0'
down_revision: Union[str, None] = '670a5f527ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reading_pace_multiplier', sa.Float(), nullable=False, server_default='1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reading_pace_multiplier')
    # ### end Alembic commands ###
