"""add qlearning state and transitions

Revision ID: 3058fde0c582
Revises: 0667c327f7a0
Create Date: 2026-08-17 09:05:46.357499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3058fde0c582'
down_revision: Union[str, None] = '0667c327f7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('q_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('state_key', sa.String(length=256), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('q_value', sa.Float(), nullable=False),
    sa.Column('update_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'state_key', 'action', name='uq_q_state_user_state_action')
    )
    op.create_index(op.f('ix_q_state_state_key'), 'q_state', ['state_key'], unique=False)
    op.create_index(op.f('ix_q_state_user_id'), 'q_state', ['user_id'], unique=False)
    op.create_table('rl_transitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('state_key', sa.String(length=256), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('next_state_key', sa.String(length=256), nullable=False),
    sa.Column('next_state_json', sa.JSON(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('policy', sa.String(length=32), nullable=False),
    sa.Column('epsilon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_rl_transitions_chat_id'), 'rl_transitions', ['chat_id'], unique=False)
    op.create_index(op.f('ix_rl_transitions_user_id'), 'rl_transitions', ['user_id'], unique=False)
    op.add_column('learning_sessions', sa.Column('rl_state_key', sa.String(length=256), nullable=True))
    op.add_column('learning_sessions', sa.Column('rl_state_json', sa.JSON(), nullable=True))
    op.add_column('learning_sessions', sa.Column('rl_action', sa.String(length=32), nullable=True))
    op.add_column('learning_sessions', sa.Column('rl_policy', sa.String(length=32), nullable=True))
    op.add_column('learning_sessions', sa.Column('rl_epsilon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_sessions', 'rl_epsilon')
    op.drop_column('learning_sessions', 'rl_policy')
    op.drop_column('learning_sessions', 'rl_action')
    op.drop_column('learning_sessions', 'rl_state_json')
    op.drop_column('learning_sessions', 'rl_state_key')
    op.drop_index(op.f('ix_rl_transitions_user_id'), table_name='rl_transitions')
    op.drop_index(op.f('ix_rl_transitions_chat_id'), table_name='rl_transitions')
    op.drop_table('rl_transitions')
    op.drop_index(op.f('ix_q_state_user_id'), table_name='q_state')
    op.drop_index(op.f('ix_q_state_state_key'), table_name='q_state')
    op.drop_table('q_state')
    # ### end Alembic commands ###
