"""add generation options

Revision ID: 670a5f527ca5
Revises: 3bc79d921612
Create Date: 2026-08-13 12:15:52.996099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670a5f527ca5'
down_revision: Union[str, None] = '3bc79d921612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_content', sa.Column('options_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_content', 'options_json')
    # ### end Alembic commands ###
