"""add generation progress tracking

Revision ID: 95c2d9b3ba09
Revises: 4bb0201c0dcc
Create Date: 2026-08-12 15:12:53.123688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c2d9b3ba09'
down_revision: Union[str, None] = '4bb0201c0dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_content', sa.Column('progress_current', sa.Integer(), nullable=True))
    op.add_column('generated_content', sa.Column('progress_total', sa.Integer(), nullable=True))
    op.add_column('generated_content', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_content', 'error_message')
    op.drop_column('generated_content', 'progress_total')
    op.drop_column('generated_content', 'progress_current')
    # ### end Alembic commands ###
